package sockowner

import (
	"encoding/binary"
	"net"
)

// FlowTupleFromOutgoingIPPacket extracts a FlowTuple from an outgoing raw IP
// packet generated by a local application.
//
// This function is designed for app-based split routing with a local MITM/TUN
// setup:
//
//	Local apps -> MITM/TUN -> outer networks
//
// It treats the packet as an outgoing packet from the local machine. Therefore:
//
//	FlowTuple.LocalIP    = packet source IP
//	FlowTuple.LocalPort  = packet source TCP/UDP port
//	FlowTuple.RemoteIP   = packet destination IP
//	FlowTuple.RemotePort = packet destination TCP/UDP port
//
// This is the correct orientation for GetSockOwner when you want to identify
// the local process that created the socket.
//
// Important usage rules:
//
//   - Pass raw IPv4/IPv6 packets, as normally read from a TUN device.
//     Do not pass Ethernet frames from a TAP device.
//   - If your TUN device was created without IFF_NO_PI, Linux may prepend a
//     4-byte packet information header. Strip that header before calling this.
//   - This function only returns flows for TCP and UDP.
//     ICMP, ICMPv6, ESP, GRE, SCTP, and other protocols return
//     ErrProtocol.
//   - Non-first IP fragments do not contain TCP/UDP ports, so they return
//     ErrNonFirstFragment.
//   - First fragments are accepted if the TCP/UDP ports are present.
//   - For incoming packets, do not use this function directly. Incoming packet
//     source/destination are reversed relative to the local socket owner.
//     Use FlowTupleFromIncomingIPPacket instead, or reverse the resulting tuple.
//
// Typical usage:
//
//	flow, err := FlowTupleFromOutgoingIPPacket(packet)
//	if err != nil {
//	    return nil // unsupported, fragmented, malformed, etc.
//	}
//	owner, err := GetSockOwner(flow)
//
// This extractor is packet-level only. It does not verify that
// the packet belongs to an existing kernel socket. GetSockOwner performs that
// best-effort socket table lookup later.
func FlowTupleFromOutgoingIPPacket(packet []byte) (FlowTuple, error) {
	return flowTupleFromIPPacket(packet, packetDirectionOutgoing)
}

// FlowTupleFromIncomingIPPacket extracts a FlowTuple from an incoming raw IP
// packet, oriented from the local socket owner's perspective.
//
// For an incoming packet:
//
//	packet source      = remote peer
//	packet destination = local app socket
//
// GetSockOwner expects:
//
//	Local*  = local app socket endpoint
//	Remote* = remote peer endpoint
//
// So this function reverses packet source/destination.
func FlowTupleFromIncomingIPPacket(packet []byte) (FlowTuple, error) {
	return flowTupleFromIPPacket(packet, packetDirectionIncoming)
}

type packetDirection int

const (
	packetDirectionOutgoing packetDirection = iota
	packetDirectionIncoming
)

func flowTupleFromIPPacket(
	packet []byte,
	dir packetDirection,
) (FlowTuple, error) {
	if len(packet) < 1 {
		return FlowTuple{}, ErrShortPacket
	}

	version := packet[0] >> 4

	switch version {
	case 4:
		return flowTupleFromIPv4Packet(packet, dir)
	case 6:
		return flowTupleFromIPv6Packet(packet, dir)
	default:
		return FlowTuple{}, ErrNotIPPacket
	}
}

func flowTupleFromIPv4Packet(
	packet []byte,
	dir packetDirection,
) (FlowTuple, error) {
	if len(packet) < 20 {
		return FlowTuple{}, ErrShortPacket
	}

	ihl := int(packet[0]&0x0f) * 4
	if ihl < 20 {
		return FlowTuple{}, ErrMalformedPacket
	}
	if len(packet) < ihl {
		return FlowTuple{}, ErrShortPacket
	}

	totalLen := int(binary.BigEndian.Uint16(packet[2:4]))
	if totalLen < ihl {
		return FlowTuple{}, ErrMalformedPacket
	}
	if len(packet) < totalLen {
		return FlowTuple{}, ErrShortPacket
	}

	// Ignore trailing bytes if caller passed a larger backing buffer.
	packet = packet[:totalLen]

	flagsFrag := binary.BigEndian.Uint16(packet[6:8])
	fragOffset := flagsFrag & 0x1fff
	if fragOffset != 0 {
		return FlowTuple{}, ErrNonFirstFragment
	}

	proto := packet[9]

	srcIP := copyIP(packet[12:16])
	dstIP := copyIP(packet[16:20])

	srcPort, dstPort, protoName, err := parseTransportPorts(packet[ihl:], proto)
	if err != nil {
		return FlowTuple{}, err
	}

	return makeFlowTuple(srcIP, srcPort, dstIP, dstPort, protoName, dir), nil
}

func flowTupleFromIPv6Packet(
	packet []byte,
	dir packetDirection,
) (FlowTuple, error) {
	if len(packet) < 40 {
		return FlowTuple{}, ErrShortPacket
	}

	payloadLen := int(binary.BigEndian.Uint16(packet[4:6]))
	if payloadLen == 0 {
		// IPv6 jumbograms are rare and require Hop-by-Hop Jumbo Payload option.
		// Supporting them correctly is unnecessary for normal TUN routing.
		return FlowTuple{}, ErrMalformedPacket
	}

	totalLen := 40 + payloadLen
	if len(packet) < totalLen {
		return FlowTuple{}, ErrShortPacket
	}

	// Ignore trailing bytes if caller passed a larger backing buffer.
	packet = packet[:totalLen]

	nextHeader := packet[6]
	offset := 40

	srcIP := copyIP(packet[8:24])
	dstIP := copyIP(packet[24:40])

	for {
		switch nextHeader {
		case ipProtoTCP, ipProtoUDP:
			srcPort, dstPort, protoName, err := parseTransportPorts(
				packet[offset:],
				nextHeader,
			)
			if err != nil {
				return FlowTuple{}, err
			}

			return makeFlowTuple(
				srcIP,
				srcPort,
				dstIP,
				dstPort,
				protoName,
				dir,
			), nil

		case ipv6ExtHopByHop, ipv6ExtRouting, ipv6ExtDestinationOptions,
			ipv6ExtMobility, ipv6ExtHIP, ipv6ExtShim6:
			var err error
			nextHeader, offset, err = skipIPv6OptionsExtHeader(packet, offset)
			if err != nil {
				return FlowTuple{}, err
			}

		case ipv6ExtFragment:
			var err error
			nextHeader, offset, err = skipIPv6FragmentHeader(packet, offset)
			if err != nil {
				return FlowTuple{}, err
			}

		case ipv6ExtAH:
			var err error
			nextHeader, offset, err = skipIPv6AHHeader(packet, offset)
			if err != nil {
				return FlowTuple{}, err
			}

		case ipv6NoNextHeader:
			return FlowTuple{}, ErrProtocol

		case ipProtoESP:
			// ESP encrypts/authenticates the inner transport header. There are no
			// visible TCP/UDP ports to extract here.
			return FlowTuple{}, ErrProtocol

		default:
			return FlowTuple{}, ErrProtocol
		}
	}
}

func parseTransportPorts(
	payload []byte,
	proto uint8,
) (srcPort uint16, dstPort uint16, protoName string, err error) {
	switch proto {
	case ipProtoTCP:
		if len(payload) < 20 {
			return 0, 0, "", ErrShortPacket
		}

		headerLen := int(payload[12]>>4) * 4
		if headerLen < 20 {
			return 0, 0, "", ErrMalformedPacket
		}
		if len(payload) < headerLen {
			return 0, 0, "", ErrShortPacket
		}

		return binary.BigEndian.Uint16(payload[0:2]),
			binary.BigEndian.Uint16(payload[2:4]),
			"tcp",
			nil

	case ipProtoUDP:
		if len(payload) < 8 {
			return 0, 0, "", ErrShortPacket
		}

		return binary.BigEndian.Uint16(payload[0:2]),
			binary.BigEndian.Uint16(payload[2:4]),
			"udp",
			nil

	default:
		return 0, 0, "", ErrProtocol
	}
}

func makeFlowTuple(
	packetSrcIP net.IP,
	packetSrcPort uint16,
	packetDstIP net.IP,
	packetDstPort uint16,
	proto string,
	dir packetDirection,
) FlowTuple {
	switch dir {
	case packetDirectionOutgoing:
		return FlowTuple{
			Proto:      proto,
			LocalIP:    packetSrcIP,
			LocalPort:  packetSrcPort,
			RemoteIP:   packetDstIP,
			RemotePort: packetDstPort,
		}

	case packetDirectionIncoming:
		return FlowTuple{
			Proto:      proto,
			LocalIP:    packetDstIP,
			LocalPort:  packetDstPort,
			RemoteIP:   packetSrcIP,
			RemotePort: packetSrcPort,
		}

	default:
		panic("unknown packet direction")
	}
}

func skipIPv6OptionsExtHeader(
	packet []byte,
	offset int,
) (nextHeader uint8, nextOffset int, err error) {
	if len(packet) < offset+2 {
		return 0, 0, ErrShortPacket
	}

	nextHeader = packet[offset]
	headerLen := (int(packet[offset+1]) + 1) * 8
	if headerLen < 8 {
		return 0, 0, ErrMalformedPacket
	}

	nextOffset = offset + headerLen
	if len(packet) < nextOffset {
		return 0, 0, ErrShortPacket
	}

	return nextHeader, nextOffset, nil
}

func skipIPv6FragmentHeader(
	packet []byte,
	offset int,
) (nextHeader uint8, nextOffset int, err error) {
	if len(packet) < offset+8 {
		return 0, 0, ErrShortPacket
	}

	nextHeader = packet[offset]

	frag := binary.BigEndian.Uint16(packet[offset+2 : offset+4])

	// Fragment offset is the high 13 bits, in 8-byte units.
	fragOffset := frag >> 3
	if fragOffset != 0 {
		return 0, 0, ErrNonFirstFragment
	}

	nextOffset = offset + 8
	return nextHeader, nextOffset, nil
}

func skipIPv6AHHeader(
	packet []byte,
	offset int,
) (nextHeader uint8, nextOffset int, err error) {
	if len(packet) < offset+2 {
		return 0, 0, ErrShortPacket
	}

	nextHeader = packet[offset]

	// AH payload length is measured in 32-bit words, minus 2.
	headerLen := (int(packet[offset+1]) + 2) * 4
	if headerLen < 8 {
		return 0, 0, ErrMalformedPacket
	}

	nextOffset = offset + headerLen
	if len(packet) < nextOffset {
		return 0, 0, ErrShortPacket
	}

	return nextHeader, nextOffset, nil
}

func copyIP(b []byte) net.IP {
	ip := make(net.IP, len(b))
	copy(ip, b)
	return ip
}

const (
	ipProtoTCP = 6
	ipProtoUDP = 17
	ipProtoESP = 50

	ipv6ExtHopByHop           = 0
	ipv6ExtRouting            = 43
	ipv6ExtFragment           = 44
	ipv6ExtAH                 = 51
	ipv6NoNextHeader          = 59
	ipv6ExtDestinationOptions = 60
	ipv6ExtMobility           = 135
	ipv6ExtHIP                = 139
	ipv6ExtShim6              = 140
)
