// Package sockowner resolves best-effort process ownership for network sockets.
//
// It can look up the owner of TCP and UDP sockets from a flow tuple, and can
// resolve the peer owner for incoming connections when the platform exposes
// enough socket metadata. Results are inherently race-prone because sockets can
// close, be reused, or be shared by multiple processes while lookup is running.
//
// See examples/sockowner for runnable TCP, UDP, and Unix-domain socket demos.
package sockowner

import (
	"errors"
	"net"
	"strings"
)

var (
	// ErrNilIP reports that a required flow IP address is nil.
	ErrNilIP = errors.New("nil IP")
	// ErrInvIP reports mixed IP families or an invalid IP address.
	ErrInvIP = errors.New("mixed or invalid IP addrs")
	// ErrAEx reports more than one exact socket owner match.
	ErrAEx = errors.New("ambiguous exact socket match")
	// ErrAUW reports more than one UDP wildcard socket owner match.
	ErrAUW = errors.New("ambiguous UDP wildcard socket match")
	// ErrConnNil reports a nil connection argument.
	ErrConnNil = errors.New("nil connection")
	// ErrAddrNil reports a connection with a nil local or remote address.
	ErrAddrNil = errors.New("nil address")
	// ErrAddrTypeUnexpected reports local and remote address type mismatch.
	ErrAddrTypeUnexpected = errors.New("addr type unexpected")
	// ErrNoOwner reports that no socket owner information is available.
	ErrNoOwner = errors.New("no socket owner info")
	// ErrProtocol reports an unsupported transport protocol.
	ErrProtocol = errors.New("protocol")
	// ErrNotIPPacket reports packet data that is not IPv4 or IPv6.
	ErrNotIPPacket = errors.New("not an IPv4 or IPv6 packet")
	// ErrShortPacket reports a packet that is too short for its headers.
	ErrShortPacket = errors.New("packet is too short")
	// ErrNonFirstFragment reports an IP fragment without a transport header.
	ErrNonFirstFragment = errors.New(
		"non-first fragment has no transport header",
	)
	// ErrMalformedPacket reports a malformed IP packet.
	ErrMalformedPacket = errors.New("malformed IP packet")
)

// FlowTuple identifies the kernel socket whose owner should be resolved.
//
// Important: LocalIP/LocalPort and RemoteIP/RemotePort are from the perspective
// of the socket whose owner you want, not necessarily from the perspective of
// your current net.Conn or from the literal packet direction.
//
// Examples:
//
//   - For an outbound TCP connection created by a local process:
//
//     LocalIP:LocalPort   = local ephemeral endpoint
//     RemoteIP:RemotePort = destination endpoint
//
//   - For a TCP connection accepted by your local listener, if you want the
//     owner of the peer process on the same host, use the reversed tuple:
//
//     LocalIP:LocalPort   = conn.RemoteAddr()
//     RemoteIP:RemotePort = conn.LocalAddr()
//
//     If you use conn.LocalAddr() as Local* and conn.RemoteAddr() as Remote*,
//     you are asking for the owner of your accepted server-side socket, usually
//     your own process.
//
//   - For an egress IP packet read from a TUN device, where the packet was
//     generated by a local process:
//
//     LocalIP:LocalPort   = packet source
//     RemoteIP:RemotePort = packet destination
//
//   - For an ingress packet that you plan to inject into the local stack:
//
//     LocalIP:LocalPort   = packet destination
//     RemoteIP:RemotePort = packet source
//
// This tuple is best-effort. It is not a stable socket identity. Between the
// time you observe a packet/connection and the time GetSockOwner runs, the
// socket may close, be reused, or be shared by multiple processes.
type FlowTuple struct {
	Proto string // "tcp" or "udp"

	LocalIP    net.IP
	LocalPort  uint16
	RemoteIP   net.IP
	RemotePort uint16
}

func (f *FlowTuple) FlowFamily() (int, error) {
	if f.LocalIP == nil || f.RemoteIP == nil {
		return 0, ErrNilIP
	}

	local4 := f.LocalIP.To4()
	remote4 := f.RemoteIP.To4()

	if local4 != nil && remote4 != nil {
		return 4, nil
	}

	local16 := f.LocalIP.To16()
	remote16 := f.RemoteIP.To16()

	if local16 != nil && remote16 != nil && local4 == nil && remote4 == nil {
		return 6, nil
	}

	return 0, ErrInvIP
}

// SocketOwner describes the best-effort owner of a socket matched by FlowTuple.
//
// PIDs may be nil when the platform can identify the socket UID but cannot map
// the socket inode back to visible processes. PIDs may contain more than one
// process because sockets can be inherited across fork, duplicated, or passed
// over Unix sockets.
//
// UID is the socket UID when available. On Linux this comes from /proc/net/*.
// This is usually the effective UID of the socket creator, not necessarily the
// current effective UID of every process that still has the socket open.
//
// GID is best-effort. Linux /proc/net/* does not expose socket GID, so the Linux
// backend fills this from the first visible owning PID's effective GID.
//
// Comm is the kernel process name from /proc/<pid>/comm for the first visible
// owning PID. On Linux this name is short and may be truncated.
//
// ProcName is the executable basename resolved from /proc/<pid>/exe for the
// first visible owning PID. It may be empty due to permissions, process exit,
// zombies, or non-standard procfs behavior.
type SocketOwner struct {
	PIDs     []int   // nil when unknown; can contain multiple visible owners
	UID      *uint32 // nil when unknown
	GID      *uint32 // nil when unknown
	Comm     string  // "" when unknown
	ProcName string  // "" when unknown
}

// GetSockOwner returns the best-effort owner of the socket matching flow.
//
// Caveats:
//
//   - The result is race-prone.
//   - PID ownership is not unique: several processes can share one socket.
//   - UID may be known even when PID is not.
//   - UDP is weaker than TCP: unconnected UDP sockets often do not have a
//     remote endpoint in kernel socket tables, so backends may fall back to
//     local-address/local-port matching.
//   - Network namespaces matter. A backend usually sees sockets only in the
//     network namespace visible to the current process.
//   - Permissions, hidepid, containers, pid namespaces, and procfs policy can
//     hide owning processes.
//   - Unsupported or restricted platforms can return a nil owner with a nil
//     error. Callers must treat a nil owner as "no usable owner information",
//     even when err is nil.
func GetSockOwner(flow FlowTuple) (*SocketOwner, error) {
	return getSockOwner(flow)
}

func addrLooksUnix(addr net.Addr) bool {
	if addr == nil {
		return false
	}

	if _, ok := addr.(*net.UnixAddr); ok {
		return true
	}

	network := strings.ToLower(addr.Network())

	return network == "unix" ||
		network == "unixgram" ||
		network == "unixpacket"
}

func normalizeFlowIP(ip net.IP) (net.IP, bool) {
	if ip == nil {
		return nil, false
	}

	if ip4 := ip.To4(); ip4 != nil {
		return append(net.IP(nil), ip4...), true
	}

	if ip16 := ip.To16(); ip16 != nil {
		return append(net.IP(nil), ip16...), true
	}

	return nil, false
}

func flowFromIPAddrs(
	proto string,
	localIP net.IP,
	localPort int,
	remoteIP net.IP,
	remotePort int,
) (*FlowTuple, error) {
	localIP, ok := normalizeFlowIP(localIP)
	if !ok {
		return nil, ErrInvIP
	}

	remoteIP, ok = normalizeFlowIP(remoteIP)
	if !ok {
		return nil, ErrInvIP
	}

	if localPort < 0 || localPort > 0xffff || remotePort < 0 ||
		remotePort > 0xffff {
		return nil, ErrInvIP
	}

	return &FlowTuple{
		Proto:      proto,
		LocalIP:    localIP,
		LocalPort:  uint16(localPort), //nolint:gosec
		RemoteIP:   remoteIP,
		RemotePort: uint16(remotePort), //nolint:gosec
	}, nil
}
